services:
  website:
    image: amakarudze/pychronicles-website:latest
    env_file: ./website/.env
    environment:
      DJANGO_SETTINGS_MODULE: website.settings.prod
      DJANGO_ENV: prod
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      blog:
        condition: service_started
    networks:
      - internal
    ports:
      - "8001:8000"

  blog:
    image: amakarudze/pychronicles-blog:latest
    env_file: ./blog/.env
    environment:
      DJANGO_SETTINGS_MODULE: blog.settings.prod
      DJANGO_ENV: prod
    entrypoint: ["./entrypoint.sh"]
    depends_on:
      blog_db:
        condition: service_healthy
    networks:
      - internal
    ports:
      - "8002:8000"

  blog_db:
    image: postgres:18
    env_file: .env 
    environment:
      POSTGRES_DB:      ${POSTGRES_DB}
      POSTGRES_USER:    ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - blog_data:/var/lib/postgresql
    networks:
      - internal

networks:
  internal:

volumes:
  blog_data:
  static_website:
  static_blog:
