# Generated by Django 5.2.8 on 2026-03-22 14:09

import json

from django.core.serializers.json import DjangoJSONEncoder
from django.db import migrations

import wagtail.blocks
import wagtail.fields


def convert_to_streamfield(apps, schema_editor):
    BlogPage = apps.get_model("core", "BlogPage")
    for page in BlogPage.objects.all():
        page.text = json.dumps(
            [{"type": "rich_text", "value": page.text}],
            cls=DjangoJSONEncoder
        )
        page.save()


def convert_to_richtext(apps, schema_editor):
    BlogPage = apps.get_model("core", "BlogPage")
    for page in BlogPage.objects.all():
        if page.text:
            stream = json.loads(page.text)
            page.body = "".join([
                child["value"] for child in stream
                if child["type"] == "rich_text"
            ])
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext,
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="text",
            field=wagtail.fields.StreamField(
                [("heading", 0), ("paragraph", 1), ("image", 2), ("markdown", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"form_classname": "title"}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtailmarkdown.blocks.MarkdownBlock", (), {}),
                },
                null=True,
            ),
        ),
    ]
