
name: Run Tests for Website
on: [push, pull_request]
jobs:
  CI-for-Website-Django-Project:
    runs-on : ubuntu-latest
    env:
      DEFAULT_FROM_EMAIL: "no-reply@example.com"

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.12"]
        poetry-version: ["2.2.1"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: View poetry --help
        run: poetry --help

      - name: Setup a local virtual environment for Website
        working-directory: ./website
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true 
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies for Website
        working-directory: ./website
        run: |
          poetry install
      - name: Run Website Migrations and Tests
        working-directory: ./website
        run: |
          poetry run python manage.py migrate
      - name: Run Website Tests
        working-directory: ./website
        run: |
          poetry run pytest --cov-branch --cov-report=xml

      - name: Upload Website coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: amakarudze/pychronicles
